# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_RextendRProto_wrappers", use_symbols = TRUE, package_name = "RextendRProto")

#' @docType package
#' @usage NULL
#' @useDynLib RextendRProto, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' return float add to R.
#' @export
add <- function(x, y) .Call(wrap__add, x, y)

#' return vector add to R.
#' @export
mult <- function(x, y) .Call(wrap__mult, x, y)

